//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillID { get; set; }
        public Nullable<int> NumOfReservedDays { get; set; }
        public int RoomNum { get; set; }
        public string Type { get; set; }
        public double RoomPrice { get; set; }
        public Nullable<double> LaundryPrice { get; set; }
        public Nullable<double> RentCarPrice { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<int> noadult { get; set; }
        public Nullable<int> nochild { get; set; }
        public Nullable<int> customerID { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
