//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOut
    {
        public int CheckOutID { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public int CheckInID { get; set; }
        public int RoomNum { get; set; }
        public int customerID { get; set; }
        public int noadults { get; set; }
        public Nullable<int> nochild { get; set; }
        public int passportnum { get; set; }
    
        public virtual CheckIn CheckIn { get; set; }
        public virtual Room Room { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
