//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int UserID { get; set; }
        public string message1 { get; set; }
        public string message2 { get; set; }
        public string message3 { get; set; }
        public string message4 { get; set; }
        public string message5 { get; set; }
        public string message6 { get; set; }
        public string message7 { get; set; }
        public string message8 { get; set; }
        public string message9 { get; set; }
        public string message10 { get; set; }
        public byte boxfull { get; set; }
    
        public virtual User User { get; set; }
    }
}
