//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int UserID_from { get; set; }
        public int UserID_to { get; set; }
        public string message1 { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual User User { get; set; }
    }
}
